language: node_js
node_js: '8'
sudo: false
before_script:
- npx bower install
script: npx gulp dev:build && npx gulp prod:build
after_success: |
  [ $TRAVIS_BRANCH = master ] &&
  [ $TRAVIS_PULL_REQUEST = false ] &&
  pip install --user ghp-import &&
  export PATH="$PATH:$HOME/.local/bin" &&
  ghp-import -n dist/dev &&
  git push -fq https://${GH_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git gh-pages
env:
  global:
  - secure: eDtqxk+pJDLb3We5DEjbtrYVu+3aiuinzKxkIy2ap7XEx54C8EReoqyfcQvCxDbPe5KACNaKrMXuI3RnEMQ6BDyz+eHW6BPgfgq5lUeIj9Ep+OgZ+NfLnurQ7ylZanO2Hy8bOXGm3E8iLF9sSfUFs6LDDOBn7B278CE0RpWDatiPXYchlt35UvqTKljjhfH1EuEHarpeO7GCZLBAe0PRSO6po+oDzAAieJ8uqH++sBuTN1BIJP6fZSyiak2DhPrXmscxkjVeffTmep9awNM0GtSze1tHSA7I1M90nDLkC9GxUjZEp6E36oUuKTiVOgLc1bRz16B+Y5C/GF1JpTwdj2eRf3gC51loqBqYDDEorLDIJV94Rk1EqxzfJUZXO34ru/WSAbQtQzgT/nuS86oPCmVV02MQ3qFobq6SuLk37Qie6HUeNGgtnH8hEHmI+R9zsqsq3jrv/txz/CjI3XgbZSrdrYKjM3/t7C5IhdXFtUvSAUwqegdHvZuglMFDYAe2FQb0iIvFMA7dYqQ42hxoo3Cmzfq+2t/BmqDMCjiKW9/SIBO+PEn7EH5Vx6EXTvB7+AS6vQr/NPDOGsCsxJYExzq4F16/dNPS1KmpemFMNTBcEBA2oON7nYDb/UNkZ+4gUjShjXmawiXTUAtewRfjJu8NKPw7sSMwFLPqGpNjT9E=
